// AUTO-GENERATED by backend/generate_puzzles.py — do not edit by hand.
// To regenerate:  cd backend && python generate_puzzles.py
//
// This file is a stub. Run the generator to populate it with compound-word puzzles.

import type { Puzzle } from './puzzles'

export const GENERATED_PUZZLES: Puzzle[] = []
